docker-compose.yaml
frontend/src/server.py

Added tracing to understand the performance and what is happening with the code.   Also fixed the frontend to make sure that the output is maintained in the session and not the full response.

Added LangSmith Tracing and fixed some bad code in the frontend

---

backend/src/graph_server.py

There was a bug where there was no system prompt that was being passed into the LLM to decide on what actions the process should take.

made a change for the to include system prompt whenever we make calls to the graph.

---

backend/src/graph_server.py
backend/src/tools/get_options_chain.py

WIll get options premium to recommend what premium I should do to buy a stock.

Added code to handle Options Chain to recommend when to get premiums.

---

.devcontainer/backend-container/devcontainer.json
.devcontainer/frontend-container/devcontainer.json
README.md
backend/src/graph_server.py
backend/src/prompts/system_prompt.py
docker-compose.yaml
frontend/requirements.txt
frontend/src/server.py

I added some change to do python interpreter for creating graphs.

More development

---

README.md
backend/requirements.txt
backend/src/graph_server.py
docker-compose.yaml
frontend/requirements.txt
frontend/src/server.py

This should be closed but added authentication to the streamlit app and the API.

Made the changes to support OAuth2 Authentication

---

README.md
backend/src/graph_server.py
docker-compose.yaml
frontend/src/server.py

CLosed.....Add ANVIRONMENT variable that will control if authentication will be enabled or  not

30 run locally without security

---

infra/deployment.bicep

Added a bicep code to deploy in Azure

12 infrastructure as code

---

backend/src/graph.py

There was a bug that it was trimming tools calls and that is a no no.

Fixed the Bug for the Trimming of Messages

---

frontend/src/server.py

Added a try to hide the KeyError for this.

Added a try except to hide the keyerror

---

backend/src/graph.py

model = AzureChatOpenAI(
azure_deployment=os.getenv("AZURE_OPENAI_MODEL"),
api_version=os.getenv("OPENAI_API_VERSION"),
temperature=0,
#streaming=True,
max_retries=3
)

Updated AzureChatOpenAI to use Environment Variables

---

backend/requirements.txt
backend/src/graph_server.py
frontend/requirements.txt
frontend/src/server.py

Fixes #45 I added the Application Insights to the Chat Application and also enabled Application Insights Live View for both the chat application and the api.

Add Application Insights to the Chat Application

---

docker-compose.yaml

Fixes #52...removed the .environmental.env and replaced it with the .env file

BUG - Remove the .environmental.env file from docker compose

---

backend/src/prompts/system_prompt.py

Fixes #60...Changed the system prompt for the Financial Services to only show if you ask a financial question.

Safety message for Financial Inquiries

---

backend/requirements.txt
backend/src/graph.py
backend/src/tools/code/python_repl_tool.py
frontend/requirements.txt

Multi-Agents

---

backend/src/graph.py

Backout Agents and go back to the old way

---

backend/src/prompts/system_prompt.py

Weather Forecasts thinks its in Celsius

---

.github/workflows/main.yml

Container Deployment in Github Action

---

backend/src/prompts/system_prompt.py

Stock Market Up or Down .  Modified the system prompt to answer that question.

---

backend/src/graph_server.py

Liveness Prob on the API

---

frontend/src/server.py

Change the StreamLit Title From server to FinanceGPT

---

backend/requirements.txt

Upgrade YFINANCE package to 0.2.50

---

backend/src/graph_server.py

BUG - Add additional logging
